config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace :admin do 
    resources :dashboard, only: [:index]
    resources :libraries
    resources :login, only: [:create, :index]
    resources :logout, only: [:index]
  end

  resources :about, only: [:index]
  resources :archive, only: [:index, :show]
  resources :contact_us, only: [:index]
  resources :events, only: [:index]
  resources :home, only: [:index]
  resources :search, only: [:index]

  namespace :ranking do 
    resources :by_followers, only: [:index]
    resources :by_mentions, only: [:index]
    resources :by_tweets, only: [:index]
  end

  namespace :stats do 
    
    namespace :over_time do 
      resources :changes_in_followers
      resources :followers 
      resources :mentions
      resources :tweets 
    end

    namespace :ratios do 
      resources :hashtags 
      resources :links
      resources :mentions 
    end

    namespace :totals do 
      resources :changes_in_followers
      resources :mentions
      resources :tweets
    end

  end


end

app/models/library.rb
class Library < ActiveRecord::Base

  include ChartHelper

  has_many :tweets

  validates :twitter_id,  :presence => true, :uniqueness => true
  validates :username,    :presence => true, :uniqueness => true

  def build_from_screename(screen_name)

    #Strip @ if it exists
    screen_name = screen_name.gsub("@", "")

    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['twitter_consumer_key']
      config.consumer_secret     = ENV['twitter_consumer_secret']
      config.access_token        = ENV['twitter_oauth_token']
      config.access_token_secret = ENV['twitter_oauth_token_secret']
    end

    user = client.user(screen_name)

    if user.id
      self.username = screen_name
      self.twitter_id = user.id
      self.save!
    end

  end

  def change_in_followers_by_date(start_date = Date.new(2012,01,01), end_date = Date.today)
    change = {}
    followers_by_date(start_date, end_date).each_cons(2) do |row_a, row_b|
      change[row_b[0]] = row_b[1] - row_a[1] 
    end
    change
  end

  def followers_by_date(start_date = Date.new(2012,01,01), end_date = Date.today)
    tweets.select("MAX(followers) AS followers, date(tweet_created_at)").between_dates(start_date, end_date).group('date(tweet_created_at)').reorder('date(tweet_created_at)').map{ |row| [row.date, row.followers] }
  end

  def mentions_by_date(start_date = Date.new(2012,01,01), end_date = Date.today)
    Tweet.unscoped.by_a_mentioner.between_dates(start_date, end_date).where("mentions @> '{#{self.username}}'::text[]").group('date(tweet_created_at)').reorder('date(tweet_created_at)').count
  end

  def ratio_of_tweets_with_hashtags(start_date = Date.new(2012,01,01), end_date = Date.today)
    total = tweets.count
    with_hashtags = tweets.where("array_upper(hashtags, 1) IS NOT NULL").count
    [with_hashtags, total - with_hashtags]
  end

  def ratio_of_tweets_with_links(start_date = Date.new(2012,01,01), end_date = Date.today)
    total = tweets.count
    with_urls = tweets.where("array_upper(urls, 1) IS NOT NULL").count
    [with_urls, total - with_urls]
  end

  def ratio_of_tweets_with_mentions(start_date = Date.new(2012,01,01), end_date = Date.today)
    total = tweets.count
    with_mentions = tweets.where("array_upper(mentions, 1) IS NOT NULL").count
    [with_mentions, total - with_mentions]
  end

  def self.rank_by_followers
    rank = {}
    ids = Tweet.unscoped.select("MAX(id) AS id").by_a_library.group(:username).collect(&:id)
    Tweet.unscoped.where(:id => ids).order('followers DESC').each do |tweet|
      rank[tweet.username] = tweet.followers
    end
    rank
  end

  def self.rank_by_mentions
    rank = {}
    Library.pluck(:username).each do |library|
      rank[library] = Tweet.unscoped.by_a_mentioner.where(" mentions @> '{#{library}}'::text[] ", library).count
    end
    rank.sort_by{|k,v| v}.reverse.to_h
  end

  def self.rank_by_tweets
    Tweet.unscoped.by_a_library.group(:username).order('count_id DESC').count(:id)
  end

  def total_change_in_followers(start_date = Date.new(2012,01,01), end_date = Date.today)
    changes = followers_by_date(start_date, end_date)
    changes.last[1] - changes.first[1]
  end

  def total_mentions(start_date = Date.new(2012,01,01), end_date = Date.today)
    Tweet.unscoped.by_a_mentioner.between_dates(start_date, end_date).where("mentions @> '{#{self.username}}'::text[]").count
  end

  def total_tweets(start_date = Date.new(2012,01,01), end_date = Date.today)
    tweets.between_dates(start_date, end_date).count
  end

  def tweets_by_date(start_date = Date.new(2012,01,01), end_date = Date.today)
    tweets.between_dates(start_date, end_date).group('date(tweet_created_at)').reorder('date(tweet_created_at)').count
  end
  
end

app/controllers/admin/libraries_controller.rb
class Admin::LibrariesController < ApplicationController

  before_action :authenticated?

  def create
    library = Library.new
    library.build_from_screename(params[:screen_name])

    if library 
      flash[:success] = "@#{library.username} added to tracker"
    else
      flash[:error] = library.errors.full_messages.to_sentence
    end

    redirect_to admin_libraries_path

  end

  def destroy

    library = Library.where(:id => params[:id]).first 

    if library
      library.delete
      flash[:success] = "Library removed from tracker"
    else
      flash[:error] = "Library could not be found"
    end

    redirect_to admin_libraries_path

  end

  def index
  end

  def restart_tracker
    system "ruby lib/tracker.rb restart"
    flash[:success] = "Tracker restarted"
  end

end

app/helpers/admin/libraries_helper.rb
module Admin::LibrariesHelper
end

app/views/admin/libraries/index.html.haml
.row
  .col-sm-12
    .box
      .box-header
        %h2
          %i.fa.fa-bank
          Libraries
      .box-content
        - if flash[:error]
          .col-xs-12
            .alert.alert-danger
              %i.fa-fw.fa.fa-times
              %strong Error!
              = flash[:error]
        - if flash[:success]
          .col-xs-12
            .alert.alert-success
              %i.fa-fw.fa.fa-check
              %strong Success!
              = flash[:success]
        = form_tag admin_libraries_path, :method => "post", :class => "form-horizontal" do
          %fieldset.col-sm-12
            .form-group
              %label.control-label(for="screen_name") Twitter screen name
              .controls.row
                .input-group.col-sm-4
                  %span.input-group-addon
                    %i.fa.fa-bank
                  %input.form-control(type="text" name="screen_name" id="screen_name" required)
                .input-group.col-sm-4
                  %button.btn.btn-primary(type="submit") Add library
        %hr
        %table.table
          %thead
            %tr 
              %th Username
              %th Twitter ID
              %th Delete
          %tbody
            - Library.order(:username).all.each do |library|
              %tr
                %td= library.username
                %td= library.twitter_id
                %td= link_to "Delete", admin_library_path(library), :method => :delete, data: { confirm: "Are you sure you want delete this library?" }